version: "3.9"

services:
  persons-pgsql:
    container_name: "persons-pgsql"
    image: "postgres:14.2"
    environment:
        - "POSTGRES_USER=persons"
        - "POSTGRES_PASSWORD=persons"
        - "POSTGRES_DB=persons"
        - "PGDATA=/var/lib/postgresql/data/pgdata"
    ports:
        - "5432:5432"
    volumes:
        - "/var/lib/postgresql/data"
