
package ru.gostev.jaxws.client;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonService", targetNamespace = "http://impl.service.jaxws.gostev.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonService {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns ru.gostev.jaxws.client.PersonSoapDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://impl.service.jaxws.gostev.ru/", className = "ru.gostev.jaxws.client.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://impl.service.jaxws.gostev.ru/", className = "ru.gostev.jaxws.client.UpdateResponse")
    @Action(input = "http://impl.service.jaxws.gostev.ru/PersonService/updateRequest", output = "http://impl.service.jaxws.gostev.ru/PersonService/updateResponse")
    public PersonSoapDto update(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns ru.gostev.jaxws.client.PersonSoapDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://impl.service.jaxws.gostev.ru/", className = "ru.gostev.jaxws.client.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://impl.service.jaxws.gostev.ru/", className = "ru.gostev.jaxws.client.CreateResponse")
    @Action(input = "http://impl.service.jaxws.gostev.ru/PersonService/createRequest", output = "http://impl.service.jaxws.gostev.ru/PersonService/createResponse")
    public PersonSoapDto create(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        XMLGregorianCalendar arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<ru.gostev.jaxws.client.PersonSoapDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFilter", targetNamespace = "http://impl.service.jaxws.gostev.ru/", className = "ru.gostev.jaxws.client.FindByFilter")
    @ResponseWrapper(localName = "findByFilterResponse", targetNamespace = "http://impl.service.jaxws.gostev.ru/", className = "ru.gostev.jaxws.client.FindByFilterResponse")
    @Action(input = "http://impl.service.jaxws.gostev.ru/PersonService/findByFilterRequest", output = "http://impl.service.jaxws.gostev.ru/PersonService/findByFilterResponse")
    public List<PersonSoapDto> findByFilter(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        XMLGregorianCalendar arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.gostev.jaxws.client.PersonSoapDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://impl.service.jaxws.gostev.ru/", className = "ru.gostev.jaxws.client.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://impl.service.jaxws.gostev.ru/", className = "ru.gostev.jaxws.client.FindByIdResponse")
    @Action(input = "http://impl.service.jaxws.gostev.ru/PersonService/findByIdRequest", output = "http://impl.service.jaxws.gostev.ru/PersonService/findByIdResponse")
    public PersonSoapDto findById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteById", targetNamespace = "http://impl.service.jaxws.gostev.ru/", className = "ru.gostev.jaxws.client.DeleteById")
    @ResponseWrapper(localName = "deleteByIdResponse", targetNamespace = "http://impl.service.jaxws.gostev.ru/", className = "ru.gostev.jaxws.client.DeleteByIdResponse")
    @Action(input = "http://impl.service.jaxws.gostev.ru/PersonService/deleteByIdRequest", output = "http://impl.service.jaxws.gostev.ru/PersonService/deleteByIdResponse")
    public boolean deleteById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

}
